#####################################################################
#																	 
#	Created by u'nSP IDE		11:47:47	07/12/03
#
#####################################################################




APPDIR	= E:\PROGRA~1\Sunplus\UNSPID~3\IDE180

OUTDIR	= .\Debug

CC	= $(APPDIR)\gcc

AS	= $(APPDIR)\xasm16

LD	= $(APPDIR)\xlink16

AR	= $(APPDIR)\xLib16

RESC	= $(APPDIR)\resc

RM	= $(APPDIR)\rm -f

INCLUDES	= -I"F:/电子竞赛/竞赛光盘内容/典型应用篇/电子竞赛—具有语音功能的水温控系统/temperature_ctrl/temperature_ctrl"

BODY	= -body SPCE061A_PROBE -bfile "$(APPDIR)\Body\SPCE061A_PROBE.cpt"

BINFILE	= "$(OUTDIR)\temperature_ctrl.S37"

ARYFILE	= "$(OUTDIR)\temperature_ctrl.ary"

SBMFILE	= "$(OUTDIR)\temperature_ctrl.sbm"

OPT	= -S -gstabs 

ASFLAGS	= -d -t2

CFLAGS	= $(OPT) -B$(APPDIR)\ $(INCLUDES) 

BINTYPE	= -as

LDFLAGS	=   

EXTRAFLAGS	= 


OBJFILES	= \
	"$(OUTDIR)\T034_16k.res" \
	"$(OUTDIR)\T046_16k.res" \
	"$(OUTDIR)\T047_16k.res" \
	"$(OUTDIR)\T048_16k.res" \
	"$(OUTDIR)\T049_16k.res" \
	"$(OUTDIR)\T050_16k.res" \
	"$(OUTDIR)\T051_16k.res" \
	"$(OUTDIR)\T052_16k.res" \
	"$(OUTDIR)\T053_16k.res" \
	"$(OUTDIR)\T054_16k.res" \
	"$(OUTDIR)\T055_16k.res" \
	"$(OUTDIR)\T056_16k.res" \
	"$(OUTDIR)\Resource.obj" \
	"$(OUTDIR)\system.obj" \
	"$(OUTDIR)\led.obj" \
	"$(OUTDIR)\main.obj" \
	"$(OUTDIR)\isr.obj" \
	"$(OUTDIR)\hardware.obj" \
	"$(OUTDIR)\key.obj" 

"$(OUTDIR)\T034_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T034.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T034.16k" "$(OUTDIR)\T034_16k.res" RES_T034_16K 

"$(OUTDIR)\T046_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T046.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T046.16k" "$(OUTDIR)\T046_16k.res" RES_T046_16K 

"$(OUTDIR)\T047_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T047.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T047.16k" "$(OUTDIR)\T047_16k.res" RES_T047_16K 

"$(OUTDIR)\T048_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T048.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T048.16k" "$(OUTDIR)\T048_16k.res" RES_T048_16K 

"$(OUTDIR)\T049_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T049.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T049.16k" "$(OUTDIR)\T049_16k.res" RES_T049_16K 

"$(OUTDIR)\T050_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T050.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T050.16k" "$(OUTDIR)\T050_16k.res" RES_T050_16K 

"$(OUTDIR)\T051_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T051.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T051.16k" "$(OUTDIR)\T051_16k.res" RES_T051_16K 

"$(OUTDIR)\T052_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T052.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T052.16k" "$(OUTDIR)\T052_16k.res" RES_T052_16K 

"$(OUTDIR)\T053_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T053.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T053.16k" "$(OUTDIR)\T053_16k.res" RES_T053_16K 

"$(OUTDIR)\T054_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T054.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T054.16k" "$(OUTDIR)\T054_16k.res" RES_T054_16K 

"$(OUTDIR)\T055_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T055.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T055.16k" "$(OUTDIR)\T055_16k.res" RES_T055_16K 

"$(OUTDIR)\T056_16k.res": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T056.16k"
	$(RESC) "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\voice\T056.16k" "$(OUTDIR)\T056_16k.res" RES_T056_16K 

"$(OUTDIR)\Resource.obj": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\Resource.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Resource.lst" -o "$(OUTDIR)\Resource.obj" "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\Resource.asm" 

"$(OUTDIR)\system.obj": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\system.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\system.lst" -o "$(OUTDIR)\system.obj" "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\system.asm" 

"$(OUTDIR)\led.obj": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\led.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\led.lst" -o "$(OUTDIR)\led.obj" "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\led.asm" 

"$(OUTDIR)\main.obj": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\main.c" ".\key.h" ".\a2000.h" ".\hardware.h" ".\sacm_user_A2000.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/main.asm" "F:/电子竞赛/竞赛光盘内容/典型应用篇/电子竞赛—具有语音功能的水温控系统/temperature_ctrl/temperature_ctrl/main.c" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\main.lst" -o "$(OUTDIR)\main.obj" "$(OUTDIR)\main.asm" 

"$(OUTDIR)\isr.obj": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\isr.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\isr.lst" -o "$(OUTDIR)\isr.obj" "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\isr.asm" 

"$(OUTDIR)\hardware.obj": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\hardware.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\hardware.lst" -o "$(OUTDIR)\hardware.obj" "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\hardware.asm" 

"$(OUTDIR)\key.obj": "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\key.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\key.lst" -o "$(OUTDIR)\key.obj" "F:\电子竞赛\竞赛光盘内容\典型应用篇\电子竞赛—具有语音功能的水温控系统\temperature_ctrl\temperature_ctrl\key.asm" 


.SUFFIXES : .c .asm .obj .s37 .tsk .res

all :	 "$(OUTDIR)" $(BINFILE)

"$(OUTDIR)" :
	if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

$(BINFILE) : $(OBJFILES) 
	$(LD) $(BINTYPE) $(ARYFILE) $(BINFILE) $(LDFLAGS) $(BODY) $(EXTRAFLAGS)

compile :	 $(OBJFILES)

clean :
	$(RM) "$(OUTDIR)\T034_16k.res" 
	$(RM) "$(OUTDIR)\T046_16k.res" 
	$(RM) "$(OUTDIR)\T047_16k.res" 
	$(RM) "$(OUTDIR)\T048_16k.res" 
	$(RM) "$(OUTDIR)\T049_16k.res" 
	$(RM) "$(OUTDIR)\T050_16k.res" 
	$(RM) "$(OUTDIR)\T051_16k.res" 
	$(RM) "$(OUTDIR)\T052_16k.res" 
	$(RM) "$(OUTDIR)\T053_16k.res" 
	$(RM) "$(OUTDIR)\T054_16k.res" 
	$(RM) "$(OUTDIR)\T055_16k.res" 
	$(RM) "$(OUTDIR)\T056_16k.res" 
	$(RM) "$(OUTDIR)\Resource.obj" 
	$(RM) "$(OUTDIR)\Resource.lst" 
	$(RM) "$(OUTDIR)\system.obj" 
	$(RM) "$(OUTDIR)\system.lst" 
	$(RM) "$(OUTDIR)\led.obj" 
	$(RM) "$(OUTDIR)\led.lst" 
	$(RM) "$(OUTDIR)\main.obj" 
	$(RM) "$(OUTDIR)\main.lst" 
	$(RM) "$(OUTDIR)\main.asm" 
	$(RM) "$(OUTDIR)\isr.obj" 
	$(RM) "$(OUTDIR)\isr.lst" 
	$(RM) "$(OUTDIR)\hardware.obj" 
	$(RM) "$(OUTDIR)\hardware.lst" 
	$(RM) "$(OUTDIR)\key.obj" 
	$(RM) "$(OUTDIR)\key.lst" 
	$(RM) $(BINFILE) $(SBMFILE) 

.c.asm:
	$(CC) $(CFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

.asm.obj:
	$(AS) $(ASFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

