//////////////////////////////////////////////////////////////////////////////////////////
// Progarm: SACM-A2000 API external definition
// Writen by: Andy
// Date: 2000/06/20
//////////////////////////////////////////////////////////////////////////////////////////

.external F_SACM_A2000_Initial;
.external F_SACM_A2000_ServiceLoop;
.external F_SACM_A2000_Play;
.external F_SACM_A2000_Stop;
.external F_SACM_A2000_Pause;
.external F_SACM_A2000_Resume;

.external F_SACM_A2000_Volume;
.external F_SACM_A2000_Status;

.external F_SACM_A2000_PcPlayInitial;

.external	F_FIQ_Service_SACM_A2000;


//========================================================================================        
// End of a2000.inc
//========================================================================================
        