#####################################################################
#																	 
#	Created by u'nSP IDE		12:02:18	07/12/03
#
#####################################################################




APPDIR	= E:\PROGRA~1\Sunplus\UNSPID~3\IDE180

OUTDIR	= .\Debug

CC	= $(APPDIR)\gcc

AS	= $(APPDIR)\xasm16

LD	= $(APPDIR)\xlink16

AR	= $(APPDIR)\xLib16

RESC	= $(APPDIR)\resc

RM	= $(APPDIR)\rm -f

INCLUDES	= -I"E:/RCL-Test"

BODY	= -body SPCE061A_EZPROBE -bfile "$(APPDIR)\Body\SPCE061A_EZPROBE.cpt"

BINFILE	= "$(OUTDIR)\RCL.S37"

ARYFILE	= "$(OUTDIR)\RCL.ary"

SBMFILE	= "$(OUTDIR)\RCL.sbm"

OPT	= -S -gstabs 

ASFLAGS	= -d -t2

CFLAGS	= $(OPT) -B$(APPDIR)\ $(INCLUDES) 

BINTYPE	= -as

LDFLAGS	=   

EXTRAFLAGS	= 


OBJFILES	= \
	"$(OUTDIR)\9_48k.res" \
	"$(OUTDIR)\1_48k.res" \
	"$(OUTDIR)\10_48k.res" \
	"$(OUTDIR)\11_48k.res" \
	"$(OUTDIR)\12_48k.res" \
	"$(OUTDIR)\13_48k.res" \
	"$(OUTDIR)\14_48k.res" \
	"$(OUTDIR)\15_48k.res" \
	"$(OUTDIR)\16_48k.res" \
	"$(OUTDIR)\17_48k.res" \
	"$(OUTDIR)\18_48k.res" \
	"$(OUTDIR)\19_48k.res" \
	"$(OUTDIR)\2_48k.res" \
	"$(OUTDIR)\20_48k.res" \
	"$(OUTDIR)\21_48k.res" \
	"$(OUTDIR)\22_48k.res" \
	"$(OUTDIR)\23_48k.res" \
	"$(OUTDIR)\24_48k.res" \
	"$(OUTDIR)\25_48k.res" \
	"$(OUTDIR)\26_48k.res" \
	"$(OUTDIR)\8_48k.res" \
	"$(OUTDIR)\3_48k.res" \
	"$(OUTDIR)\4_48k.res" \
	"$(OUTDIR)\5_48k.res" \
	"$(OUTDIR)\6_48k.res" \
	"$(OUTDIR)\7_48k.res" \
	"$(OUTDIR)\0_48k.res" \
	"$(OUTDIR)\27_48k.res" \
	"$(OUTDIR)\Resource.obj" \
	"$(OUTDIR)\main.obj" \
	"$(OUTDIR)\sys.obj" \
	"$(OUTDIR)\key.obj" \
	"$(OUTDIR)\hardware.obj" \
	"$(OUTDIR)\FIQ.obj" \
	"$(OUTDIR)\DISPLAY.obj" 

"$(OUTDIR)\9_48k.res": "E:\RCL-Test\voice\9.48k"
	$(RESC) "E:\RCL-Test\voice\9.48k" "$(OUTDIR)\9_48k.res" RES_9_48K 

"$(OUTDIR)\1_48k.res": "E:\RCL-Test\voice\1.48k"
	$(RESC) "E:\RCL-Test\voice\1.48k" "$(OUTDIR)\1_48k.res" RES_1_48K 

"$(OUTDIR)\10_48k.res": "E:\RCL-Test\voice\10.48k"
	$(RESC) "E:\RCL-Test\voice\10.48k" "$(OUTDIR)\10_48k.res" RES_10_48K 

"$(OUTDIR)\11_48k.res": "E:\RCL-Test\voice\11.48k"
	$(RESC) "E:\RCL-Test\voice\11.48k" "$(OUTDIR)\11_48k.res" RES_11_48K 

"$(OUTDIR)\12_48k.res": "E:\RCL-Test\voice\12.48k"
	$(RESC) "E:\RCL-Test\voice\12.48k" "$(OUTDIR)\12_48k.res" RES_12_48K 

"$(OUTDIR)\13_48k.res": "E:\RCL-Test\voice\13.48k"
	$(RESC) "E:\RCL-Test\voice\13.48k" "$(OUTDIR)\13_48k.res" RES_13_48K 

"$(OUTDIR)\14_48k.res": "E:\RCL-Test\voice\14.48k"
	$(RESC) "E:\RCL-Test\voice\14.48k" "$(OUTDIR)\14_48k.res" RES_14_48K 

"$(OUTDIR)\15_48k.res": "E:\RCL-Test\voice\15.48k"
	$(RESC) "E:\RCL-Test\voice\15.48k" "$(OUTDIR)\15_48k.res" RES_15_48K 

"$(OUTDIR)\16_48k.res": "E:\RCL-Test\voice\16.48k"
	$(RESC) "E:\RCL-Test\voice\16.48k" "$(OUTDIR)\16_48k.res" RES_16_48K 

"$(OUTDIR)\17_48k.res": "E:\RCL-Test\voice\17.48k"
	$(RESC) "E:\RCL-Test\voice\17.48k" "$(OUTDIR)\17_48k.res" RES_17_48K 

"$(OUTDIR)\18_48k.res": "E:\RCL-Test\voice\18.48k"
	$(RESC) "E:\RCL-Test\voice\18.48k" "$(OUTDIR)\18_48k.res" RES_18_48K 

"$(OUTDIR)\19_48k.res": "E:\RCL-Test\voice\19.48k"
	$(RESC) "E:\RCL-Test\voice\19.48k" "$(OUTDIR)\19_48k.res" RES_19_48K 

"$(OUTDIR)\2_48k.res": "E:\RCL-Test\voice\2.48k"
	$(RESC) "E:\RCL-Test\voice\2.48k" "$(OUTDIR)\2_48k.res" RES_2_48K 

"$(OUTDIR)\20_48k.res": "E:\RCL-Test\voice\20.48k"
	$(RESC) "E:\RCL-Test\voice\20.48k" "$(OUTDIR)\20_48k.res" RES_20_48K 

"$(OUTDIR)\21_48k.res": "E:\RCL-Test\voice\21.48k"
	$(RESC) "E:\RCL-Test\voice\21.48k" "$(OUTDIR)\21_48k.res" RES_21_48K 

"$(OUTDIR)\22_48k.res": "E:\RCL-Test\voice\22.48k"
	$(RESC) "E:\RCL-Test\voice\22.48k" "$(OUTDIR)\22_48k.res" RES_22_48K 

"$(OUTDIR)\23_48k.res": "E:\RCL-Test\voice\23.48k"
	$(RESC) "E:\RCL-Test\voice\23.48k" "$(OUTDIR)\23_48k.res" RES_23_48K 

"$(OUTDIR)\24_48k.res": "E:\RCL-Test\voice\24.48k"
	$(RESC) "E:\RCL-Test\voice\24.48k" "$(OUTDIR)\24_48k.res" RES_24_48K 

"$(OUTDIR)\25_48k.res": "E:\RCL-Test\voice\25.48k"
	$(RESC) "E:\RCL-Test\voice\25.48k" "$(OUTDIR)\25_48k.res" RES_25_48K 

"$(OUTDIR)\26_48k.res": "E:\RCL-Test\voice\26.48k"
	$(RESC) "E:\RCL-Test\voice\26.48k" "$(OUTDIR)\26_48k.res" RES_26_48K 

"$(OUTDIR)\8_48k.res": "E:\RCL-Test\voice\8.48k"
	$(RESC) "E:\RCL-Test\voice\8.48k" "$(OUTDIR)\8_48k.res" RES_8_48K 

"$(OUTDIR)\3_48k.res": "E:\RCL-Test\voice\3.48k"
	$(RESC) "E:\RCL-Test\voice\3.48k" "$(OUTDIR)\3_48k.res" RES_3_48K 

"$(OUTDIR)\4_48k.res": "E:\RCL-Test\voice\4.48k"
	$(RESC) "E:\RCL-Test\voice\4.48k" "$(OUTDIR)\4_48k.res" RES_4_48K 

"$(OUTDIR)\5_48k.res": "E:\RCL-Test\voice\5.48k"
	$(RESC) "E:\RCL-Test\voice\5.48k" "$(OUTDIR)\5_48k.res" RES_5_48K 

"$(OUTDIR)\6_48k.res": "E:\RCL-Test\voice\6.48k"
	$(RESC) "E:\RCL-Test\voice\6.48k" "$(OUTDIR)\6_48k.res" RES_6_48K 

"$(OUTDIR)\7_48k.res": "E:\RCL-Test\voice\7.48k"
	$(RESC) "E:\RCL-Test\voice\7.48k" "$(OUTDIR)\7_48k.res" RES_7_48K 

"$(OUTDIR)\0_48k.res": "E:\RCL-Test\voice\0.48k"
	$(RESC) "E:\RCL-Test\voice\0.48k" "$(OUTDIR)\0_48k.res" RES_0_48K 

"$(OUTDIR)\27_48k.res": "E:\RCL-Test\voice\27.48k"
	$(RESC) "E:\RCL-Test\voice\27.48k" "$(OUTDIR)\27_48k.res" RES_27_48K 

"$(OUTDIR)\Resource.obj": "E:\RCL-Test\Resource.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Resource.lst" -o "$(OUTDIR)\Resource.obj" "E:\RCL-Test\Resource.asm" 

"$(OUTDIR)\main.obj": "E:\RCL-Test\main.c" ".\s480.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/main.asm" "E:/RCL-Test/main.c" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\main.lst" -o "$(OUTDIR)\main.obj" "$(OUTDIR)\main.asm" 

"$(OUTDIR)\sys.obj": "E:\RCL-Test\sys.asm" ".\Hardware.inc" ".\key.inc" ".\resource.inc" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\sys.lst" -o "$(OUTDIR)\sys.obj" "E:\RCL-Test\sys.asm" 

"$(OUTDIR)\key.obj": "E:\RCL-Test\key.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\key.lst" -o "$(OUTDIR)\key.obj" "E:\RCL-Test\key.asm" 

"$(OUTDIR)\hardware.obj": "E:\RCL-Test\hardware.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\hardware.lst" -o "$(OUTDIR)\hardware.obj" "E:\RCL-Test\hardware.asm" 

"$(OUTDIR)\FIQ.obj": "E:\RCL-Test\FIQ.asm" ".\S480.inc" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\FIQ.lst" -o "$(OUTDIR)\FIQ.obj" "E:\RCL-Test\FIQ.asm" 

"$(OUTDIR)\DISPLAY.obj": "E:\RCL-Test\DISPLAY.c" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/DISPLAY.asm" "E:/RCL-Test/DISPLAY.c" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\DISPLAY.lst" -o "$(OUTDIR)\DISPLAY.obj" "$(OUTDIR)\DISPLAY.asm" 


.SUFFIXES : .c .asm .obj .s37 .tsk .res

all :	 "$(OUTDIR)" $(BINFILE)

"$(OUTDIR)" :
	if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

$(BINFILE) : $(OBJFILES) 
	$(LD) $(BINTYPE) $(ARYFILE) $(BINFILE) $(LDFLAGS) $(BODY) $(EXTRAFLAGS)

compile :	 $(OBJFILES)

clean :
	$(RM) "$(OUTDIR)\9_48k.res" 
	$(RM) "$(OUTDIR)\1_48k.res" 
	$(RM) "$(OUTDIR)\10_48k.res" 
	$(RM) "$(OUTDIR)\11_48k.res" 
	$(RM) "$(OUTDIR)\12_48k.res" 
	$(RM) "$(OUTDIR)\13_48k.res" 
	$(RM) "$(OUTDIR)\14_48k.res" 
	$(RM) "$(OUTDIR)\15_48k.res" 
	$(RM) "$(OUTDIR)\16_48k.res" 
	$(RM) "$(OUTDIR)\17_48k.res" 
	$(RM) "$(OUTDIR)\18_48k.res" 
	$(RM) "$(OUTDIR)\19_48k.res" 
	$(RM) "$(OUTDIR)\2_48k.res" 
	$(RM) "$(OUTDIR)\20_48k.res" 
	$(RM) "$(OUTDIR)\21_48k.res" 
	$(RM) "$(OUTDIR)\22_48k.res" 
	$(RM) "$(OUTDIR)\23_48k.res" 
	$(RM) "$(OUTDIR)\24_48k.res" 
	$(RM) "$(OUTDIR)\25_48k.res" 
	$(RM) "$(OUTDIR)\26_48k.res" 
	$(RM) "$(OUTDIR)\8_48k.res" 
	$(RM) "$(OUTDIR)\3_48k.res" 
	$(RM) "$(OUTDIR)\4_48k.res" 
	$(RM) "$(OUTDIR)\5_48k.res" 
	$(RM) "$(OUTDIR)\6_48k.res" 
	$(RM) "$(OUTDIR)\7_48k.res" 
	$(RM) "$(OUTDIR)\0_48k.res" 
	$(RM) "$(OUTDIR)\27_48k.res" 
	$(RM) "$(OUTDIR)\Resource.obj" 
	$(RM) "$(OUTDIR)\Resource.lst" 
	$(RM) "$(OUTDIR)\main.obj" 
	$(RM) "$(OUTDIR)\main.lst" 
	$(RM) "$(OUTDIR)\main.asm" 
	$(RM) "$(OUTDIR)\sys.obj" 
	$(RM) "$(OUTDIR)\sys.lst" 
	$(RM) "$(OUTDIR)\key.obj" 
	$(RM) "$(OUTDIR)\key.lst" 
	$(RM) "$(OUTDIR)\hardware.obj" 
	$(RM) "$(OUTDIR)\hardware.lst" 
	$(RM) "$(OUTDIR)\FIQ.obj" 
	$(RM) "$(OUTDIR)\FIQ.lst" 
	$(RM) "$(OUTDIR)\DISPLAY.obj" 
	$(RM) "$(OUTDIR)\DISPLAY.lst" 
	$(RM) "$(OUTDIR)\DISPLAY.asm" 
	$(RM) $(BINFILE) $(SBMFILE) 

.c.asm:
	$(CC) $(CFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

.asm.obj:
	$(AS) $(ASFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

