#####################################################################
#																	 
#	Created by u'nSP IDE		01:21:28	07/12/03
#
#####################################################################




APPDIR	= D:\PROGRA~1\Sunplus\UNSPID~2\IDE180

OUTDIR	= .\Debug

CC	= $(APPDIR)\gcc

AS	= $(APPDIR)\xasm16

LD	= $(APPDIR)\xlink16

AR	= $(APPDIR)\xLib16

RESC	= $(APPDIR)\resc

RM	= $(APPDIR)\rm -f

INCLUDES	= -I"F:/DXJH/e_design/Data_Sample/release/DataCollection_code/DataCollection_Host"

BODY	= -body SPCE061A_EZPROBE -bfile "$(APPDIR)\Body\SPCE061A_EZPROBE.cpt"

BINFILE	= "$(OUTDIR)\DataCollection_Host.S37"

ARYFILE	= "$(OUTDIR)\DataCollection_Host.ary"

SBMFILE	= "$(OUTDIR)\DataCollection_Host.sbm"

OPT	= -S -gstabs

ASFLAGS	= -d -t2

CFLAGS	= $(OPT) -B$(APPDIR)\ $(INCLUDES) 

BINTYPE	= -as

LDFLAGS	=   

EXTRAFLAGS	= 


OBJFILES	= \
	"$(OUTDIR)\9_72k.res" \
	"$(OUTDIR)\10_72k.res" \
	"$(OUTDIR)\11_72k.res" \
	"$(OUTDIR)\12_72k.res" \
	"$(OUTDIR)\13_72k.res" \
	"$(OUTDIR)\14_72k.res" \
	"$(OUTDIR)\15_72k.res" \
	"$(OUTDIR)\16_72k.res" \
	"$(OUTDIR)\17_72k.res" \
	"$(OUTDIR)\18_72k.res" \
	"$(OUTDIR)\19_72k.res" \
	"$(OUTDIR)\2_72k.res" \
	"$(OUTDIR)\20_72k.res" \
	"$(OUTDIR)\21_72k.res" \
	"$(OUTDIR)\22_72k.res" \
	"$(OUTDIR)\3_72k.res" \
	"$(OUTDIR)\4_72k.res" \
	"$(OUTDIR)\5_72k.res" \
	"$(OUTDIR)\6_72k.res" \
	"$(OUTDIR)\7_72k.res" \
	"$(OUTDIR)\8_72k.res" \
	"$(OUTDIR)\1_72k.res" \
	"$(OUTDIR)\Resource.obj" \
	"$(OUTDIR)\main.obj" \
	"$(OUTDIR)\uart.obj" \
	"$(OUTDIR)\System.obj" \
	"$(OUTDIR)\Key.obj" \
	"$(OUTDIR)\hardware.obj" \
	"$(OUTDIR)\ISR.obj" \
	"$(OUTDIR)\UART_DataSample.obj" \
	"$(OUTDIR)\LedShow.obj" \
	"$(OUTDIR)\SpeechPlay.obj" \
	"$(OUTDIR)\KeyHandle.obj" 

"$(OUTDIR)\9_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\9.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\9.72k" "$(OUTDIR)\9_72k.res" RES_9_72K 

"$(OUTDIR)\10_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\10.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\10.72k" "$(OUTDIR)\10_72k.res" RES_10_72K 

"$(OUTDIR)\11_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\11.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\11.72k" "$(OUTDIR)\11_72k.res" RES_11_72K 

"$(OUTDIR)\12_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\12.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\12.72k" "$(OUTDIR)\12_72k.res" RES_12_72K 

"$(OUTDIR)\13_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\13.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\13.72k" "$(OUTDIR)\13_72k.res" RES_13_72K 

"$(OUTDIR)\14_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\14.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\14.72k" "$(OUTDIR)\14_72k.res" RES_14_72K 

"$(OUTDIR)\15_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\15.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\15.72k" "$(OUTDIR)\15_72k.res" RES_15_72K 

"$(OUTDIR)\16_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\16.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\16.72k" "$(OUTDIR)\16_72k.res" RES_16_72K 

"$(OUTDIR)\17_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\17.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\17.72k" "$(OUTDIR)\17_72k.res" RES_17_72K 

"$(OUTDIR)\18_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\18.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\18.72k" "$(OUTDIR)\18_72k.res" RES_18_72K 

"$(OUTDIR)\19_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\19.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\19.72k" "$(OUTDIR)\19_72k.res" RES_19_72K 

"$(OUTDIR)\2_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\2.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\2.72k" "$(OUTDIR)\2_72k.res" RES_2_72K 

"$(OUTDIR)\20_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\20.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\20.72k" "$(OUTDIR)\20_72k.res" RES_20_72K 

"$(OUTDIR)\21_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\21.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\21.72k" "$(OUTDIR)\21_72k.res" RES_21_72K 

"$(OUTDIR)\22_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\22.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\22.72k" "$(OUTDIR)\22_72k.res" RES_22_72K 

"$(OUTDIR)\3_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\3.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\3.72k" "$(OUTDIR)\3_72k.res" RES_3_72K 

"$(OUTDIR)\4_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\4.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\4.72k" "$(OUTDIR)\4_72k.res" RES_4_72K 

"$(OUTDIR)\5_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\5.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\5.72k" "$(OUTDIR)\5_72k.res" RES_5_72K 

"$(OUTDIR)\6_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\6.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\6.72k" "$(OUTDIR)\6_72k.res" RES_6_72K 

"$(OUTDIR)\7_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\7.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\7.72k" "$(OUTDIR)\7_72k.res" RES_7_72K 

"$(OUTDIR)\8_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\8.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\8.72k" "$(OUTDIR)\8_72k.res" RES_8_72K 

"$(OUTDIR)\1_72k.res": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\1.72k"
	$(RESC) "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\voice\1.72k" "$(OUTDIR)\1_72k.res" RES_1_72K 

"$(OUTDIR)\Resource.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\Resource.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Resource.lst" -o "$(OUTDIR)\Resource.obj" "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\Resource.asm" 

"$(OUTDIR)\main.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\main.c" ".\main.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/main.asm" "F:/DXJH/e_design/Data_Sample/release/DataCollection_code/DataCollection_Host/main.c" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\main.lst" -o "$(OUTDIR)\main.obj" "$(OUTDIR)\main.asm" 

"$(OUTDIR)\uart.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\uart.asm" ".\hardware.inc" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\uart.lst" -o "$(OUTDIR)\uart.obj" "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\uart.asm" 

"$(OUTDIR)\System.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\System.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\System.lst" -o "$(OUTDIR)\System.obj" "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\System.asm" 

"$(OUTDIR)\Key.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\Key.asm" ".\hardware.inc" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\Key.lst" -o "$(OUTDIR)\Key.obj" "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\Key.asm" 

"$(OUTDIR)\hardware.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\hardware.asm" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\hardware.lst" -o "$(OUTDIR)\hardware.obj" "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\hardware.asm" 

"$(OUTDIR)\ISR.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\ISR.asm" ".\hardware.inc" ".\S480.inc" ".\Resource.inc" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\ISR.lst" -o "$(OUTDIR)\ISR.obj" "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\ISR.asm" 

"$(OUTDIR)\UART_DataSample.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\UART_DataSample.c" ".\main.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/UART_DataSample.asm" "F:/DXJH/e_design/Data_Sample/release/DataCollection_code/DataCollection_Host/UART_DataSample.c" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\UART_DataSample.lst" -o "$(OUTDIR)\UART_DataSample.obj" "$(OUTDIR)\UART_DataSample.asm" 

"$(OUTDIR)\LedShow.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\LedShow.c" ".\main.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/LedShow.asm" "F:/DXJH/e_design/Data_Sample/release/DataCollection_code/DataCollection_Host/LedShow.c" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\LedShow.lst" -o "$(OUTDIR)\LedShow.obj" "$(OUTDIR)\LedShow.asm" 

"$(OUTDIR)\SpeechPlay.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\SpeechPlay.c" ".\s480.h" ".\main.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/SpeechPlay.asm" "F:/DXJH/e_design/Data_Sample/release/DataCollection_code/DataCollection_Host/SpeechPlay.c" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\SpeechPlay.lst" -o "$(OUTDIR)\SpeechPlay.obj" "$(OUTDIR)\SpeechPlay.asm" 

"$(OUTDIR)\KeyHandle.obj": "F:\DXJH\e_design\Data_Sample\release\DataCollection_code\DataCollection_Host\KeyHandle.c" ".\main.h" 
	$(CC) $(CFLAGS) -o "$(OUTDIR)/KeyHandle.asm" "F:/DXJH/e_design/Data_Sample/release/DataCollection_code/DataCollection_Host/KeyHandle.c" 
	$(AS) $(ASFLAGS) $(INCLUDES) -l "$(OUTDIR)\KeyHandle.lst" -o "$(OUTDIR)\KeyHandle.obj" "$(OUTDIR)\KeyHandle.asm" 


.SUFFIXES : .c .asm .obj .s37 .tsk .res

all :	 "$(OUTDIR)" $(BINFILE)

"$(OUTDIR)" :
	if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

$(BINFILE) : $(OBJFILES) 
	$(LD) $(BINTYPE) $(ARYFILE) $(BINFILE) $(LDFLAGS) $(BODY) $(EXTRAFLAGS)

compile :	 $(OBJFILES)

clean :
	$(RM) "$(OUTDIR)\9_72k.res" 
	$(RM) "$(OUTDIR)\10_72k.res" 
	$(RM) "$(OUTDIR)\11_72k.res" 
	$(RM) "$(OUTDIR)\12_72k.res" 
	$(RM) "$(OUTDIR)\13_72k.res" 
	$(RM) "$(OUTDIR)\14_72k.res" 
	$(RM) "$(OUTDIR)\15_72k.res" 
	$(RM) "$(OUTDIR)\16_72k.res" 
	$(RM) "$(OUTDIR)\17_72k.res" 
	$(RM) "$(OUTDIR)\18_72k.res" 
	$(RM) "$(OUTDIR)\19_72k.res" 
	$(RM) "$(OUTDIR)\2_72k.res" 
	$(RM) "$(OUTDIR)\20_72k.res" 
	$(RM) "$(OUTDIR)\21_72k.res" 
	$(RM) "$(OUTDIR)\22_72k.res" 
	$(RM) "$(OUTDIR)\3_72k.res" 
	$(RM) "$(OUTDIR)\4_72k.res" 
	$(RM) "$(OUTDIR)\5_72k.res" 
	$(RM) "$(OUTDIR)\6_72k.res" 
	$(RM) "$(OUTDIR)\7_72k.res" 
	$(RM) "$(OUTDIR)\8_72k.res" 
	$(RM) "$(OUTDIR)\1_72k.res" 
	$(RM) "$(OUTDIR)\Resource.obj" 
	$(RM) "$(OUTDIR)\Resource.lst" 
	$(RM) "$(OUTDIR)\main.obj" 
	$(RM) "$(OUTDIR)\main.lst" 
	$(RM) "$(OUTDIR)\main.asm" 
	$(RM) "$(OUTDIR)\uart.obj" 
	$(RM) "$(OUTDIR)\uart.lst" 
	$(RM) "$(OUTDIR)\System.obj" 
	$(RM) "$(OUTDIR)\System.lst" 
	$(RM) "$(OUTDIR)\Key.obj" 
	$(RM) "$(OUTDIR)\Key.lst" 
	$(RM) "$(OUTDIR)\hardware.obj" 
	$(RM) "$(OUTDIR)\hardware.lst" 
	$(RM) "$(OUTDIR)\ISR.obj" 
	$(RM) "$(OUTDIR)\ISR.lst" 
	$(RM) "$(OUTDIR)\UART_DataSample.obj" 
	$(RM) "$(OUTDIR)\UART_DataSample.lst" 
	$(RM) "$(OUTDIR)\UART_DataSample.asm" 
	$(RM) "$(OUTDIR)\LedShow.obj" 
	$(RM) "$(OUTDIR)\LedShow.lst" 
	$(RM) "$(OUTDIR)\LedShow.asm" 
	$(RM) "$(OUTDIR)\SpeechPlay.obj" 
	$(RM) "$(OUTDIR)\SpeechPlay.lst" 
	$(RM) "$(OUTDIR)\SpeechPlay.asm" 
	$(RM) "$(OUTDIR)\KeyHandle.obj" 
	$(RM) "$(OUTDIR)\KeyHandle.lst" 
	$(RM) "$(OUTDIR)\KeyHandle.asm" 
	$(RM) $(BINFILE) $(SBMFILE) 

.c.asm:
	$(CC) $(CFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

.asm.obj:
	$(AS) $(ASFLAGS) $(INCLUDES) -o "$(OUTDIR)/$@" $<

