extern void bzero(char*, unsigned);
extern char* memccpy(char*,char*,char,int);
extern char* memchr(char*,char,int);
extern int memcmp(char*,char*,int);
extern int bcmp(char*,char*,int);
extern char* memcpy(char*,char*,unsigned);
extern char* memmove(char*,char*,unsigned);
extern void bcopy(char*,char*,unsigned);
extern char* memset(char*,char,unsigned);
extern void movmem(char*,char*,unsigned);
extern void setmem(char*,int,char);
extern char* stpcpy(char*,char*);
extern int strcasecmp(char*, char*);
extern char* strcat(char*,char*);
extern char* strchr(const char *, int);
extern char* strdup(const char *);
extern char* index(char*,char);
extern int strcmp(char*,char*);
extern int strcoll(char*,char*);
extern char* strcpy(char*,char*);
extern int strcspn(char*,char*);
extern unsigned strlen(char*);
extern char* strlwr(char*);
extern char* strncat(char*,char*,int);
extern int strncmp(char*,char*,int);
extern char* strncpy(char*,char*,int);
extern char* strnset(char*,char,unsigned);
extern char* strpbrk(char*,char*);
extern char* strrchr(char*,char);
extern char* rindex(char*,char);
extern int strncasecmp(char*, char*, int);
extern char* strrev(char*);
extern char* strset(char*,char);
extern int strspn(char*,char*);
extern char* strstr(char*,char*);
extern char* strtok(char*,char*);
extern char* strupr(char*);
extern int strxfrm(char*,const char*, int);
extern void swab(const char*,char*,unsigned int);
extern void* charpack(void *dst,char *s);		//wwy add
extern void* charunpack(void *dst,void *s);
extern char* strerror(int);						//wwy add
